/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package generator_layout;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */
public class createPaper extends javax.swing.JFrame {
Connection connection = DBConnection.getConnection();
    /**
     * Creates new form createPaper
     */
   String Marks;

    public createPaper() {
      initComponents(); //To change body of generated methods, choose Tools | Templates.
    }
    public void getpost(String a){
        
         //   mark.setText(a);
            System.out.println(a);
}
   
    public createPaper(String a) {
       
       this.Marks=a;
       initComponents();
        
       mark.setText(Marks);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        schoolname = new javax.swing.JTextField();
        typeof_paper = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        time = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        sem = new javax.swing.JComboBox<>();
        mark = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        level = new javax.swing.JComboBox<>();
        subject = new javax.swing.JComboBox<>();
        subcode = new javax.swing.JComboBox<>();
        class1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("School name");

        jLabel2.setText("Typeofpaper");

        jLabel3.setText("Subject");

        jLabel4.setText("Subcode");

        jLabel5.setText("Class");

        schoolname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolnameActionPerformed(evt);
            }
        });

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Max Marks");

        jLabel7.setText("Time Allowed");

        time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30 minutes", "1 hour", "1.5 hour", "2 hour", "2.5 hour", "3 hour" }));

        jLabel8.setText("Semester ");

        sem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semActionPerformed(evt);
            }
        });

        jLabel9.setText("Complexity Level of Paper");

        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "low", "medium", "hard", " " }));
        level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelActionPerformed(evt);
            }
        });

        subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "software engineering", "Dbms", "Computer networks", "operating system", " " }));

        subcode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ce-302", "ce-301", "ce-303" }));

        class1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "computer engineering", "electronics engineering" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(33, 33, 33)
                        .addComponent(level, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(time, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(schoolname)
                            .addComponent(typeof_paper)
                            .addComponent(sem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mark)
                            .addComponent(subject, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subcode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(class1, 0, 199, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(schoolname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(typeof_paper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(subcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(class1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Question Paper Generator");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jMenu2.setText("Home");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu1.setText("Back");
        jMenu1.setFont(new java.awt.Font("Bradley Hand ITC", 0, 18)); // NOI18N
        jMenu1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jMenu1FocusGained(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Back");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void schoolnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
       String school=schoolname.getText();
       String typeofpaper=typeof_paper.getText();
         String Subject =subject.getSelectedItem().toString();
           String Subjectcode =subcode.getSelectedItem().toString();
         String Class=class1.getSelectedItem().toString();
         String Time=time.getSelectedItem().toString();   
   //String compulque="",quemarks="";
         String Semester=sem.getSelectedItem().toString();
        String Complexitylevel=level.getSelectedItem().toString();
    // String Marks=mark.getText();
    System.out.println(Marks);
    if(!(school.isEmpty()&& typeofpaper.isEmpty() && Subject.isEmpty()&& Subjectcode.isEmpty() &&Class.isEmpty()  )){
   
        
 try{
      PreparedStatement ps9=connection.prepareStatement("select  Compulsoryque, eachquemark from queoption where Queno='1' and ROWNUM<=1 ");
             ResultSet rs0=ps9.executeQuery();
              String quemark="",compulque="";
             while(rs0.next()){
                compulque= rs0.getString("Compulsoryque");
             System.out.println("compulsoryque**************="+compulque);
             quemark=rs0.getString("eachquemark");
             System.out.println("eachque**************="+quemark);
             }      
     
     
     PreparedStatement ps910=connection.prepareStatement("select COUNT(*) AS value from dataEntry where branchname=?\n" +
"and course=?and courseid=? and semester=? and complexitylevel=? and quemarks=? and ROWNUM <=? ");

               ps910.setString(1,Class );
            ps910.setString(2,Subject );
             ps910.setString(3,Subjectcode );
              ps910.setString(4,Semester );
               ps910.setString(5,Complexitylevel );
                ps910.setString(6,quemark );
                 ps910.setString(7,compulque );
            ResultSet rs910 = ps910.executeQuery();
             int value=0;
             while(rs910.next()){
                value= rs910.getInt("value");
                  System.out.println(" ***********compul value :==="+value);
             }
               PreparedStatement pp=connection.prepareStatement("select  Compulsoryque, eachquemark from queoption where Queno='2' and ROWNUM<=1 ");
             ResultSet rsp=pp.executeQuery();
              String quemark2="",compulque2="";
             while(rsp.next()){
                compulque2= rsp.getString("Compulsoryque");
             System.out.println("compulsoryque 2*****************="+compulque2);
             quemark2=rsp.getString("eachquemark");
               System.out.println("eachque2 *********** ="+quemark2);
             }      
     
     
     PreparedStatement pz=connection.prepareStatement("select COUNT(*) AS value from dataEntry where branchname=?\n" +
"and course=?and courseid=? and semester=? and complexitylevel=? and quemarks=? and ROWNUM <=? ");

               pz.setString(1,Class );
            pz.setString(2,Subject );
             pz.setString(3,Subjectcode );
              pz.setString(4,Semester );
               pz.setString(5,Complexitylevel );
                pz.setString(6,quemark2 );
                 pz.setString(7,compulque2 );
            ResultSet rsz = pz.executeQuery();
             int value1=0;
             while(rsz.next()){
                value1= rsz.getInt("value");
                System.out.println(" comp   value1************ :==="+value1);
             }
      PreparedStatement pm=connection.prepareStatement("select  Compulsoryque, eachquemark from queoption where Queno='3' and ROWNUM<=1 ");
             ResultSet rsi=pm.executeQuery();
              String quemark3="",compulque3="";
             while(rsi.next()){
                compulque3= rsi.getString("Compulsoryque");
            System.out.println("compulsoryque3 **************** ="+compulque3);
             quemark3=rsi.getString("eachquemark");
             System.out.println("eachque3 ki 3 mark*****************="+quemark3);
             }      
     
     
     PreparedStatement psi=connection.prepareStatement("select COUNT(*) AS value from dataEntry where branchname=?\n" +
"and course=?and courseid=? and semester=? and complexitylevel=? and quemarks=? and ROWNUM <=? ");

               psi.setString(1,Class );
            psi.setString(2,Subject );
             psi.setString(3,Subjectcode );
              psi.setString(4,Semester );
               psi.setString(5,Complexitylevel );
                psi.setString(6,quemark3 );
                 psi.setString(7,compulque3 );
            ResultSet rspo = psi.executeQuery();
             int value2=0;
             while(rspo.next()){
                value2= rspo.getInt("value");
                System.out.println(" value2***************** :="+value2);
             }
    
            if(value>=(Integer.parseInt(compulque)) &&value1>=(Integer.parseInt(compulque2)) && value2>=(Integer.parseInt(compulque3))){
                     generator_layout.pdf.fetch(school,typeofpaper,Subject,Subjectcode,Class, Marks,Time,Semester,Complexitylevel);
   
                
            }
            else
            {
                ImageIcon icon = new ImageIcon( "E:\\NetBeansProjects\\Question_paper_generator\\src\\generator_layout\\download(5)" );
 
JOptionPane.showMessageDialog(null,"Please add more questions", "IMP", JOptionPane.INFORMATION_MESSAGE, icon );
                     
            }
 } catch (Exception e) {
            e.printStackTrace();
           ImageIcon icon = new ImageIcon( "E:\\NetBeansProjects\\Question_paper_generator\\src\\generator_layout\\download(5)" );
 
JOptionPane.showMessageDialog(null, "SQLException", "IMP", JOptionPane.INFORMATION_MESSAGE, icon );
                   
        }
    /*
                   
                              ImageIcon icon = new ImageIcon("E:\\NetBeansProjects\\Question_paper_generator\\src\\generator_layout\\download(5)" );
 
JOptionPane.showMessageDialog(null, "Save", " Downloaded successfully", JOptionPane.INFORMATION_MESSAGE, icon );
    this.dispose();
       try {
           sleep(100);
       } catch (InterruptedException ex) {
           Logger.getLogger(createPaper.class.getName()).log(Level.SEVERE, null, ex);
       }
    frontpapge.main(null);
    }}
                    else
                    {
                              ImageIcon icon = new ImageIcon( "E:\\NetBeansProjects\\Question_paper_generator\\src\\generator_layout\\download(5)" );
 
JOptionPane.showMessageDialog(null, "Error", "Not Downloaded successfully", JOptionPane.INFORMATION_MESSAGE, icon );
                             // JOptionPane.showMessageDialog(null, "Not Downloaded successfully", "250","450", "C:\\Users\\USER\\Downloads\\pdficon");
                            */
                            }
    
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semActionPerformed

    private void levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
       pattern opf=new pattern();
        opf.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenu1FocusGained
        // TODO add your handling code here:
        this.dispose();
        pattern opf=new pattern();
        opf.setVisible(true);
    }//GEN-LAST:event_jMenu1FocusGained

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
       pattern opf=new pattern();
        opf.setVisible(true);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
         this.dispose();
       frontpapge opf=new frontpapge();
        opf.setVisible(true);
    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createPaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createPaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createPaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createPaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createPaper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> class1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JTextField mark;
    private javax.swing.JTextField schoolname;
    private javax.swing.JComboBox<String> sem;
    private javax.swing.JComboBox<String> subcode;
    private javax.swing.JComboBox<String> subject;
    private javax.swing.JComboBox<String> time;
    private javax.swing.JTextField typeof_paper;
    // End of variables declaration//GEN-END:variables
}
